---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgANN+fyIcRAQ/fhwTefAkFaCx1I/D9tGehGJgdeOC7vTcddu73k1nUZgilnuikya4gR9uHpHywnRUFaP2S9Gj0wrzVnp0BLEiYM3OTvpl1kfPpr9OhcX1Hy0oN/HvZXdJzNPqdaxfISArTW12BekdaFAYY28JWNAPX3BI4cqg63++MktDWv/K8MkXLRAABAWvysPBQvck8CbqCSwIiGJr8wOgwmQHxqgpoeR5dqFeGcq6aUXnBeULEzxgi/3y5Jir8Ex6FMs4DpYnAVw978xcf+89cDyu7d2SF5StnuRNK5/lE/aIw0aNUA8vXWuiA0x/TV/8V6qptsKnfRYZNe25mpGULC2KC4geYcTGvJfW6ZBwkxcChrXiojeMSlX+KE+DmrPWGKK54UBAA3wlc7wFJuwOiYq6fPLlD2fA4l/9PtbaSEA0K1nwlxmHL7y6ozi3yuthdnuI1VThDsEd+biUnb+2w8z7zETy4pQsVL2ldzY/wsoIemF+2X0YPhsljIDlHso9mPxuVQZaJ3doiJinbX1AZIOEdIqtlJiJsWZTWt3P/ylowKXGhIpKbs5vzkuPt13GQAqq+2X/xizJWOT4KRyeTe8FpJitotCu1shXpqtyyuvfClC23YC8m4IFc4YgEHf6pbJkJMitdzbNJEOh/M/GTPvO5AktNaOYPjiiIpAr/VH/OX2Fi9fmqoLH340vqIqJn94hIXtl/atQDnXqHvXcz6
    STRIPE_API_KEY: AgA9v1dMYkQwipq0gCRWHqKJmNPfvKKGiF4CNdP+YWj//mm2SFmSwq9RadXQMeqaiUQg+mO6PAMmOjZdIxnWlYFdE+hRMRaR47QHNF9/BnJQg19SGOJRQAqb1PObyhrQHwyv/t01zeSuL2rJQacDzc8GRLwqBBsmeY+mN6nfqgnXMHDAXS0Xcp4O7tlC5cVUpMjfL/Vvl3RkTeAeGdmRRi+A7m0+9TjmFGPfKZLrhQWMYXc7RsmYoDYJBXlDC2dv5SwHrf92uBxpjQoF6IwQhB+C8d98smLQBWeNAnyFASYh87oUmz860FQ864ZZQxfJKImfZHjjxSbNf+ziyF/+fptvbvV+bVrEpB4Pn05MBIbKjVDP4fhMjQGoIHe/mdGbYkJcl9CbPGqj6qInRSOi16pVIwrLkbfDVvU2pdoou6/ZQSk+wi+i3+KsR/HYPjv+VyvwpPr4jd5EeYGIlXxs/MZSrJmDs2Hc9VP9AzeUb3jFERwbBGFbFHja2mEkUa4/v6YFiV5bDHXaV56LX207RCWb9HuKAlK1Lr4WYlQqTmQlAAwQ98nwfF6Vom7n2tuT4SkhFuaozpI58Nex7vvVtudV3gZHSWm94D/eP4zO1LBRk4H0mTP/aSrUNDo/TCKZIw8AyMHhlBnYk0rwkXWc3KxElLZ+6/4YzpV6w4bDJ5gGh9PFmsegfdcbaMwmYfKpeslFHo3HtORjuuMH/x1ZpV4QDHaVJcc=
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
