apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    STRIPE_API_KEY: AgDummyEncryptedStripeKeyReplaceWithKubesealOutput==
    DB_PASSWORD: AgDummyEncryptedPasswordReplaceWithKubesealOutput==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque